export const ActionTypes = {
ADD_TASK: 'ADD_TASK',
REMOVE_TASK : 'REMOVE_TASK',
SEE_DETAILS:'SEE_DETAILS',
TOGGLE_TASK : 'TOGGLE_TASK',
SET_VISIBILITY_FILTER : 'SET_VISIBILITY_FILTER',
  SHOW_ALL: 'SHOW_ALL',
  SHOW_TODO: 'SHOW_TODO',
  SHOW_INPROGRESS: 'SHOW_INPROGRESS',
  SHOW_DONE:'SHOW_DONE'
  };
  
  